No product errors.

Test defect error:
page = <Page url='https://www.overstock.com/search?q=!%40%23%24%25%5E%26*()_%2B'>
param = '!@#$%^&*()_+'

    @pytest.mark.parametrize("param", data)
    def test_search(page: Page, param):
        query = param
        page.goto("https://www.overstock.com/")
    
        # home page
        home_page = HomePage(page)
        home_page.close_dialog()
        home_page.search_for(query)
        page.wait_for_load_state()
        results_page = ResultsPage(page)
>       results_page.assert_title(query)

test_searchBar.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\overstock\pages\resultsPage.py:47: in assert_title
    title = self.search_title.inner_text(timeout=3000)
..\venv\lib\site-packages\playwright\sync_api\_generated.py:16500: in inner_text
    self._sync(self._impl_obj.inner_text(timeout=timeout))
..\venv\lib\site-packages\playwright\_impl\_locator.py:444: in inner_text
    return await self._frame.inner_text(
..\venv\lib\site-packages\playwright\_impl\_frame.py:618: in inner_text
    return await self._channel.send("innerText", locals_to_params(locals()))
..\venv\lib\site-packages\playwright\_impl\_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <playwright._impl._connection.Connection object at 0x000002066DD48AC0>
cb = <function Channel.send.<locals>.<lambda> at 0x000002066DD92C20>
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -> Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
>           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.TimeoutError: Locator.inner_text: Timeout 3000ms exceeded.
E           Call log:
E           waiting for locator("#sr-root>[class^='_title']")

..\venv\lib\site-packages\playwright\_impl\_connection.py:514: TimeoutError
